apiVersion: 1

datasources:
  - name: MySQL-SNMP
    uid: MySQL-SNMP
    type: mysql
    url: mysql:3306
    user: root
    secureJsonData:
      password: "Surya@2006"
    database: mon
    jsonData:
      sslMode: "skip-verify"
    access: proxy
    isDefault: true
